export const CATEGORY_LABELS_FA = {
  coffee: "Coffee",
  nastaran: "Nastaran",
  food_dining: "غذا و رستوران",
  groceries: "خرید روزانه",
  transportation: "حمل‌ونقل",
  health: "سلامت",
  subscriptions: "اشتراک",
  shopping: "خرید",
  housing: "مسکن",
  education: "آموزش",
  entertainment: "تفریح",
  personal_care: "مراقبت شخصی",
  travel: "سفر",
  gifts: "هدیه",
  utilities: "قبوض",
  car: "خودرو",
  debts: "بدهی و قرض",
  other: "سایر",
};

export const CATEGORY_COLORS = {
  coffee: "#8B5E3C",
  nastaran: "#D66BA0",
  food_dining: "#4F86C6",
  groceries: "#63B995",
  transportation: "#F0A500",
  health: "#E06C75",
  subscriptions: "#C678DD",
  shopping: "#56B6C2",
  housing: "#D19A66",
  education: "#98C379",
  entertainment: "#E5C07B",
  personal_care: "#BE5046",
  travel: "#61AFEF",
  gifts: "#FF7EB3",
  utilities: "#ABB2BF",
  car: "#528BFF",
  debts: "#F44747",
  other: "#7A7A7A",
};
