export const DEFAULT_CATEGORIES = [
  { key: "coffee", label: "قهوه", color: "#8B5E3C" },
  { key: "nastaran", label: "نسترن", color: "#D66BA0" },
  { key: "food_dining", label: "غذا و رستوران", color: "#4F86C6" },
  { key: "groceries", label: "خرید روزانه", color: "#63B995" },
  { key: "transportation", label: "حمل‌ونقل", color: "#F0A500" },
  { key: "health", label: "سلامت", color: "#E06C75" },
  { key: "subscriptions", label: "اشتراک", color: "#C678DD" },
  { key: "shopping", label: "خرید", color: "#56B6C2" },
  { key: "housing", label: "مسکن", color: "#D19A66" },
  { key: "education", label: "آموزش", color: "#98C379" },
  { key: "entertainment", label: "تفریح", color: "#E5C07B" },
  { key: "personal_care", label: "مراقبت شخصی", color: "#BE5046" },
  { key: "travel", label: "سفر", color: "#61AFEF" },
  { key: "gifts", label: "هدیه", color: "#FF7EB3" },
  { key: "utilities", label: "قبوض", color: "#ABB2BF" },
  { key: "car", label: "خودرو", color: "#528BFF" },
  { key: "debts", label: "بدهی و قرض", color: "#F44747" },
  { key: "other", label: "سایر", color: "#7A7A7A" },
];
