export const CATEGORY_LABELS_FA = {
  coffee: "قهوه",
  nastaran: "نسترن",
  food_dining: "غذا و رستوران",
  groceries: "خرید روزانه",
  transportation: "حمل‌ونقل",
  health: "سلامت",
  subscriptions: "اشتراک",
  shopping: "خرید",
  housing: "مسکن",
  education: "آموزش",
  entertainment: "تفریح",
  personal_care: "مراقبت شخصی",
  travel: "سفر",
  gifts: "هدیه",
  utilities: "قبوض",
  car: "خودرو",
  debts: "بدهی و قرض",
  other: "سایر",
};

export const CATEGORY_EMOJIS = {
  coffee: "☕",
  nastaran: "🌸",
  food_dining: "🍽️",
  groceries: "🛒",
  transportation: "🚕",
  health: "💊",
  subscriptions: "📱",
  shopping: "🛍️",
  housing: "🏠",
  education: "📚",
  entertainment: "🎬",
  personal_care: "🧴",
  travel: "✈️",
  gifts: "🎁",
  utilities: "💡",
  car: "🚗",
  debts: "💳",
  other: "🧾",
};
